In [1]:
# Descriptive statistics

In [2]:
import numpy as np
v=np.array([2,5,4,9,3,8])
v

array([2, 5, 4, 9, 3, 8])

In [3]:
np.var(v)

np.float64(6.472222222222222)

In [4]:
np.std(v)

np.float64(2.544056253745625)

In [5]:
m=np.mean(v)
m

np.float64(5.166666666666667)

In [6]:
y=m-v
y

array([ 3.16666667,  0.16666667,  1.16666667, -3.83333333,  2.16666667,
       -2.83333333])

In [7]:
b=y**2
b

array([10.02777778,  0.02777778,  1.36111111, 14.69444444,  4.69444444,
        8.02777778])

In [8]:
u=np.sum(b)/len(v)
u

np.float64(6.472222222222222)

In [9]:
c=np.sqrt(u)
c

np.float64(2.544056253745625)

In [10]:
# x=np.array([5,10,5,11,12,4,3,2,7,1])
# y=np.array([1,6,2,8,5,1,4,6,5,2

In [11]:
# df.corr()  used for co-realtion 
# df.cov() used for co-variance

In [12]:
import pandas as pd

In [13]:
df=pd.read_excel(r"C:\Users\asus\Desktop\Datasets\co-relation_dataset.xlsx")
df

    X  Y
0   5  1
1  10  6
2   5  2
3  11  8
4  12  5
5   4  1
6   3  4
7   2  6
8   7  5
9   1  2

In [14]:
df.corr()     # for co-relation

          X         Y
X  1.000000  0.575026
Y  0.575026  1.000000

In [15]:
df.cov()      # for co variance

           X         Y
X  14.888889  5.333333
Y   5.333333  5.777778

In [16]:
df.var()           # for variance

X    14.888889
Y     5.777778
dtype: float64

In [17]:
df2=pd.read_excel(r"C:\Users\asus\Desktop\Datasets\co-variance.xlsx")
df2

    X   Y
0   2  12
1   4  11
2   6   8
3   8   3
4  10   1

In [18]:
df2.var()

X    10.0
Y    23.5
dtype: float64

In [19]:
df2.corr()

          X         Y
X  1.000000 -0.978492
Y -0.978492  1.000000

In [20]:
df2.cov()

      X     Y
X  10.0 -15.0
Y -15.0  23.5

In [21]:
# Inferential statistics

In [1]:
# Hypothesis testing:
# 1. T-test
# 2. Z-test
# 3. Chisquare test
# 4. Anova test

In [ ]:
# Determine the whether the average weight of a sample of a 20 mangoes is significally different from the population average 
weight of 70 grams. the sample mean weight is 70.55 grams